name: 'call-vertexai-on-prompt'

on:
  push:
    paths:
      - '.github/workflows/call-vertexai-on-prompt.yml'
      - 'prompts/**'
  workflow_dispatch:

jobs:
  check-prompts:
    runs-on: ['self-hosted', 'linux']

    env:
      VERTEXAI_CREDENTIALS: ${{ secrets.VERTEXAI_CREDENTIALS }}

    steps:
      - uses: 'actions/checkout@v4'

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: read_action_js
        with:
          config: ${{ github.workspace }}/prompts/prompt1.yml

      - name: use-yaml-file
        run: |
          echo method: ${{ steps.read_action_js.outputs['method'] }}
          echo modelName: ${{ steps.read_action_js.outputs['modelName'] }}
          echo history: ${{ steps.read_action_js.outputs['history'] }}
          echo message: ${{ steps.read_action_js.outputs['message'] }}
          echo temperature: ${{ steps.read_action_js.outputs['temperature'] }}
          echo topp: ${{ steps.read_action_js.outputs['topp'] }}
          echo topk: ${{ steps.read_action_js.outputs['topk'] }}
          echo candidateCount: ${{ steps.read_action_js.outputs['candidateCount'] }}
          echo maxOutputTokens: ${{ steps.read_action_js.outputs['maxOutputTokens'] }}
          echo stopSequences: ${{ steps.read_action_js.outputs['stopSequences'] }}

      - name: Run vertexai-action
        id: run-vertexai-action
        uses: docker://ghcr.io/sabralod/vertexai-action:go-action
        with:
          method: ${{ steps.read_action_js.outputs['method'] }}
          projectId: 'test-project-1-420005'
          region: 'us-central1'
          modelName: ${{ steps.read_action_js.outputs['modelName'] }}
          credentialsFile: ''
          credentials: "${{ env.VERTEXAI_CREDENTIALS }}"
          message: ${{ steps.read_action_js.outputs['message'] }}
          temperature: ${{ steps.read_action_js.outputs['temperature'] }}
          topp: ${{ steps.read_action_js.outputs['topp'] }}
          topk: ${{ steps.read_action_js.outputs['topk'] }}
          candidateCount: ${{ steps.read_action_js.outputs['candidateCount'] }}
          maxOutputTokens: ${{ steps.read_action_js.outputs['maxOutputTokens'] }}
          stopSequences: ${{ steps.read_action_js.outputs['stopSequences'] }}
          history: ${{ steps.read_action_js.outputs['history'] }}

      - name: Print response
        run: |
          echo 'output time is ${{ steps.run-vertexai-action.outputs.time }}'
          echo 'prompt message is ${{ steps.run-vertexai-action.with.message.value }}'
          echo 'prompt response is ${{ steps.run-vertexai-action.outputs.response }}'

      # - name: Check if yq is installed
      #   run: yq --version
      #   continue-on-error: true

      # - name: Install yq
      #   if: failure()
      #   run: sudo apt-get update && sudo apt-get install yq -y

      # - name: Read YAML file
      #   id: read-yaml
      #   run: |
      #     value=$(yq eval '.message' prompts/prompt1.yml)
      #     echo "::set-output name=message::$value"
      #     value=$(yq eval '.history' prompts/prompt1.yml)
      #     echo "::set-output name=history::$value"

      # - name: Print value
      #   run: |
      #     echo 'Value: ${{ steps.read-yaml.outputs.message }}'
      #     echo 'Value: ${{ steps.read-yaml.outputs.history }}'
          