name: 'vertexai-action'

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ['self-hosted', 'linux']
    steps:
      - uses: 'actions/checkout@v4'
      
      - uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go.mod'
      
      - uses: 'https://github.com/sabralod/vertexai-action@go-action'