name: 'vertexai-action'

on:
  push:
  workflow_dispatch:

jobs:
  run-vertexai-action:
    runs-on: ['self-hosted', 'linux']
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'vertexai-action'
        uses: sabralod/vertexai-action@go-action
        with:
          projectId: 'test-project-1-420005'
          region: 'us-central1'
          modelName: 'gemini-1.0-pro-vision'


      # - name: Checkout vertexai-action repository
      #   id: checkout-vertexai-action
      #   uses: actions/checkout@v4
      #   with:
      #     repository: sabralod/vertexai-action
      #     ref: go-action
      #     token: ${{ secrets.VERTEXAI_ACTION_TOKEN }}
      #     path: ./.github/actions/vertexai-action
      
      # - uses: 'actions/setup-go@v5'
      #   with:
      #     go-version-file: './.github/actions/vertexai-action/go.mod'
      
      # - name: Run vertexai-action
      #   uses: ./.github/actions/vertexai-action/action.yml
      #   with:
      #     projectId: 'test-project-1-420005'
      #     region: 'us-central1'
      #     modelName: 'gemini-1.0-pro-vision'