name: 'vertexai-action'

on:
  push:
  workflow_dispatch:

jobs:
  run-vertexai-action:
    runs-on: ['self-hosted', 'linux']
    steps:
      - uses: 'actions/checkout@v4'

      - name: Checkout vertexai-action repository
        uses: actions/checkout@v4
        with:
          repository: sabralod/vertexai-action
          ref: go-action
          token: ${{ secrets.VERTEXAI_ACTION_TOKEN }}
          path: ./.github/actions/vertexai-action
      
      - uses: 'actions/setup-go@v5'
        with:
          go-version-file: './.github/actions/vertexai-action/go.mod'
          
      
      - name: Run vertexai-action
        uses: ./.github/actions/vertexai-action/action
